jobs:
  - job: displayListOfName
    steps:
      - template: templates-practice/parameters/templates-parameters-define-names.yml
        parameters:
          listOfName:
            - "Anh"
            - "Tuan"
      - template: templates-practice/parameters/templates-parameters-run-steps-names.yml

