parameters:
  - name: jobName
    default: ''
  - name: vmImage
    default: ''

jobs:
  - job: ${{ parameters.jobName }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - script: npm install
      - script: npm test