jobs:
  - job: Ubuntu
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: echo "Hello World!"
  - job: Window
    pool:
      vmImage: 'windows-latest'
    steps:
      - bash: echo "Hello World!"