name: 'Delete old workflows'

on:
  push:
    branches:
      - main
      - features/*
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.TOKEN_EXECUTE }}
          expire-in: 7days # workflow will be deleted automatically if they are older than 7 days